name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v --enable-code-coverage
    - name: Locate code coverage
      run: |
        echo "::set-output name=CODECOV_PATH::$(swift test --show-codecov-path)"
      id: locate-code-coverage
    - uses: codecov/codecov-action@v2
      with:
        files: ${{ steps.locate-code-coverage.outputs.CODECOV_PATH }}
